_BASE_: 'mile.yml'

LOG_DIR: 'tensorboard_logs'
TAG: 'debug'

GPUS: 1
BATCHSIZE: 1

STEPS: 4
LOGGING_INTERVAL: 2
LOG_VIDEO_INTERVAL: 4
VAL_CHECK_INTERVAL: 4
LIMIT_VAL_BATCHES: 2
N_WORKERS: 0

PREDICTION:
  N_SAMPLES: 1

OPTIMIZER:
  ACCUMULATE_GRAD_BATCHES: 1

SEMANTIC_SEG:
  ENABLED: False

VOXEL_SEG:
  ENABLED: False
  DIMENSION: 32
  N_CLASSES: 9
  USE_WEIGHTS: True

LIDAR_SEG:
  ENABLED: False
  N_CLASSES: 9
  USE_WEIGHTS: True

LIDAR_RE:
  ENABLED: True

SEMANTIC_IMAGE:
  ENABLED: False
  N_CLASSES: 9
  USE_WEIGHTS: True

DEPTH:
  ENABLED: False

LOSSES:
  RGB_INSTANCE: False
  SSIM: False

MODEL:
  EMBEDDING_DIM: 512
  TRANSFORMER:
    ENABLED: False

EVAL:
  RGB_SUPERVISION: True

RECEPTIVE_FIELD: 6
FUTURE_HORIZON: 6

PRETRAINED:
#  PATH: 'weights/epoch=37-step=57600.ckpt'
  PATH: 'weights/epoch=65-step=99000.ckpt'
#  PATH: 'weights/epoch=65-step=99000_transformer.ckpt'
#  PATH: ''
#
#DATASET:
#  DATAROOT: ''
#  VERSION: 'mini'
