_BASE_: 'mile.yml'

LOG_DIR: 'tensorboard_logs'
TAG: 'debug'

GPUS: 1
BATCHSIZE: 1

STEPS: 8
LOGGING_INTERVAL: 2
VAL_CHECK_INTERVAL: 4
LIMIT_VAL_BATCHES: 2
N_WORKERS: 0

DATASET:
  DATAROOT: ''
  VERSION: 'mini'
