_BASE_: 'mile.yml'

LOG_DIR: 'tensorboard_logs'
TAG: 'debug'

GPUS: 1
BATCHSIZE: 1

STEPS: 8
LOGGING_INTERVAL: 2
LOG_VIDEO_INTERVAL: 4
VAL_CHECK_INTERVAL: 4
LIMIT_VAL_BATCHES: 2
N_WORKERS: 0

VOXEL_SEG:
  ENABLED: False
  DIMENSION: 32
  N_CLASSES: 9
  USE_WEIGHTS: True

LIDAR_SEG:
  ENABLED: False
  N_CLASSES: 9
  USE_WEIGHTS: True

SEMANTIC_IMAGE:
  ENABLED: False
  N_CLASSES: 9
  USE_WEIGHTS: True

DEPTH:
  ENABLED: False

LOSSES:
  RGB_INSTANCE: False
  SSIM: False

MODEL:
  EMBEDDING_DIM: 64

EVAL:
  RGB_SUPERVISION: True

#PRETRAINED:
#  PATH: 'weights/epoch=37-step=57600.ckpt'
#
#DATASET:
#  DATAROOT: ''
#  VERSION: 'mini'
