_BASE_: 'mile.yml'

LOG_DIR: 'tensorboard_logs'
TAG: 'debug'

GPUS: 1
BATCHSIZE: 1

STEPS: 8
LOGGING_INTERVAL: 2
VAL_CHECK_INTERVAL: 4
LIMIT_VAL_BATCHES: 2
N_WORKERS: 0

VOXEL_SEG:
  DIMENSION: 32
  ENABLED: True

LIDAR_SEG:
  ENABLED: True

MODEL:
  EMBEDDING_DIM: 256

#DATASET:
#  DATAROOT: ''
#  VERSION: 'mini'
