_BASE_: 'mile.yml'

LOG_DIR: 'tensorboard_logs'
TAG: 'debug'

GPUS: 1
BATCHSIZE: 1

STEPS: 8
LOGGING_INTERVAL: 2
LOG_VIDEO_INTERVAL: 4
VAL_CHECK_INTERVAL: 4
LIMIT_VAL_BATCHES: 2
N_WORKERS: 0

VOXEL_SEG:
  DIMENSION: 128
  ENABLED: False

LIDAR_SEG:
  ENABLED: False

LOSSES:
  RGB_INSTANCE: False
  SSIM: False

MODEL:
  EMBEDDING_DIM: 128

#DATASET:
#  DATAROOT: ''
#  VERSION: 'mini'
