LOG_DIR: 'tensorboard_logs'
TAG: 'mile'

CML_PROJECT: 'MasterThesis/world_model'
CML_TASK: 'mile'
CML_TYPE: 'training'

GPUS: 1
BATCHSIZE: 1
STEPS: 100000
VAL_CHECK_INTERVAL: 40
LOGGING_INTERVAL: 20
LOG_VIDEO_INTERVAL: 40
N_WORKERS: 1

OPTIMIZER:
  ACCUMULATE_GRAD_BATCHES: 4

EVAL:
  RGB_SUPERVISION: True

RECEPTIVE_FIELD: 1
FUTURE_HORIZON: 1

PRETRAINED:
  PATH: ''

DATASET:
  DATAROOT: '/mnt/d/python/dataset/test/'

IMAGE:
  CAMERA_POSITION: [0.5, 0.0, 2.0]  # (forward, right, up)
